/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 28e66e5fab712a21d82055d81608a145)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env {
		POLAR_MODE: "sandbox";
		POLAR_ACCESS_TOKEN: "polar_oat_...";
		POLAR_WEBHOOK_SECRET: "polar_whs_...";
		POLAR_SUCCESS_URL: "http://localhost:5173/";
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "POLAR_MODE" | "POLAR_ACCESS_TOKEN" | "POLAR_WEBHOOK_SECRET" | "POLAR_SUCCESS_URL">> {}
}
